CREATE TABLE team (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    season_id BIGINT NOT NULL REFERENCES season(id) ON DELETE CASCADE,
    provider_name VARCHAR(50) NOT NULL,
    external_team_id BIGINT NOT NULL,
    team_name VARCHAR(150) NOT NULL,
    short_code VARCHAR(20),
    country_name VARCHAR(100),
    founded_year INTEGER,
    national_flag BOOLEAN NOT NULL DEFAULT FALSE,
    logo_url TEXT,
    venue_name VARCHAR(150),
    venue_city VARCHAR(150),
    venue_capacity INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_team_season_provider_external
        UNIQUE (season_id, provider_name, external_team_id)
);

CREATE TABLE fixture (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    season_id BIGINT NOT NULL REFERENCES season(id) ON DELETE CASCADE,
    provider_name VARCHAR(50) NOT NULL,
    external_fixture_id BIGINT NOT NULL,
    referee_name VARCHAR(150),
    timezone_name VARCHAR(100),
    kickoff_at TIMESTAMPTZ NOT NULL,
    status_long VARCHAR(100),
    status_short VARCHAR(20),
    elapsed_minutes INTEGER,
    league_round VARCHAR(100),
    home_team_id BIGINT REFERENCES team(id),
    away_team_id BIGINT REFERENCES team(id),
    home_goals INTEGER,
    away_goals INTEGER,
    halftime_home_goals INTEGER,
    halftime_away_goals INTEGER,
    fulltime_home_goals INTEGER,
    fulltime_away_goals INTEGER,
    extratime_home_goals INTEGER,
    extratime_away_goals INTEGER,
    penalty_home_goals INTEGER,
    penalty_away_goals INTEGER,
    venue_name VARCHAR(150),
    venue_city VARCHAR(150),
    raw_status_json JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_fixture_season_provider_external
        UNIQUE (season_id, provider_name, external_fixture_id)
);

CREATE TABLE fixture_team (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fixture_id BIGINT NOT NULL REFERENCES fixture(id) ON DELETE CASCADE,
    team_id BIGINT NOT NULL REFERENCES team(id) ON DELETE CASCADE,
    side VARCHAR(10) NOT NULL,
    winner_flag BOOLEAN,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_fixture_team_side
        CHECK (side IN ('HOME', 'AWAY')),
    CONSTRAINT uq_fixture_team_fixture_side
        UNIQUE (fixture_id, side),
    CONSTRAINT uq_fixture_team_fixture_team
        UNIQUE (fixture_id, team_id)
);

CREATE INDEX idx_team_season ON team(season_id);
CREATE INDEX idx_fixture_season ON fixture(season_id);
CREATE INDEX idx_fixture_kickoff_at ON fixture(kickoff_at);
CREATE INDEX idx_fixture_home_team ON fixture(home_team_id);
CREATE INDEX idx_fixture_away_team ON fixture(away_team_id);
CREATE INDEX idx_fixture_team_fixture ON fixture_team(fixture_id);