CREATE TABLE player (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_name VARCHAR(50) NOT NULL,
    external_player_id BIGINT NOT NULL,
    player_name VARCHAR(150) NOT NULL,
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    age INTEGER,
    birth_date DATE,
    nationality VARCHAR(100),
    height_text VARCHAR(30),
    weight_text VARCHAR(30),
    injured_flag BOOLEAN NOT NULL DEFAULT FALSE,
    photo_url TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_player_provider_external
        UNIQUE (provider_name, external_player_id)
);

CREATE TABLE team_player_squad (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    season_id BIGINT NOT NULL REFERENCES season(id) ON DELETE CASCADE,
    team_id BIGINT NOT NULL REFERENCES team(id) ON DELETE CASCADE,
    player_id BIGINT NOT NULL REFERENCES player(id) ON DELETE CASCADE,
    shirt_number INTEGER,
    position_name VARCHAR(50),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_team_player_squad
        UNIQUE (season_id, team_id, player_id)
);

CREATE TABLE fixture_team_sheet (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fixture_id BIGINT NOT NULL REFERENCES fixture(id) ON DELETE CASCADE,
    team_id BIGINT NOT NULL REFERENCES team(id) ON DELETE CASCADE,
    formation VARCHAR(20),
    coach_external_id BIGINT,
    coach_name VARCHAR(150),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_fixture_team_sheet
        UNIQUE (fixture_id, team_id)
);

CREATE TABLE fixture_lineup (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fixture_id BIGINT NOT NULL REFERENCES fixture(id) ON DELETE CASCADE,
    team_id BIGINT NOT NULL REFERENCES team(id) ON DELETE CASCADE,
    player_id BIGINT REFERENCES player(id),
    lineup_type VARCHAR(20) NOT NULL,
    player_name VARCHAR(150) NOT NULL,
    shirt_number INTEGER,
    position_code VARCHAR(20),
    grid_coordinate VARCHAR(20),
    captain_flag BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_fixture_lineup_type
        CHECK (lineup_type IN ('STARTING', 'SUBSTITUTE')),
    CONSTRAINT uq_fixture_lineup_entry
        UNIQUE (fixture_id, team_id, lineup_type, player_name)
);

CREATE TABLE fixture_absence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fixture_id BIGINT NOT NULL REFERENCES fixture(id) ON DELETE CASCADE,
    team_id BIGINT NOT NULL REFERENCES team(id) ON DELETE CASCADE,
    player_id BIGINT REFERENCES player(id),
    player_name VARCHAR(150) NOT NULL,
    absence_type VARCHAR(50),
    reason_text VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_fixture_absence_entry
        UNIQUE (fixture_id, team_id, player_name, absence_type, reason_text)
);

CREATE INDEX idx_player_external ON player(provider_name, external_player_id);
CREATE INDEX idx_team_player_squad_team ON team_player_squad(team_id);
CREATE INDEX idx_fixture_team_sheet_fixture ON fixture_team_sheet(fixture_id);
CREATE INDEX idx_fixture_lineup_fixture ON fixture_lineup(fixture_id);
CREATE INDEX idx_fixture_absence_fixture ON fixture_absence(fixture_id);