CREATE TABLE fixture_team_stat (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fixture_id BIGINT NOT NULL REFERENCES fixture(id) ON DELETE CASCADE,
    team_id BIGINT NOT NULL REFERENCES team(id) ON DELETE CASCADE,
    stat_name VARCHAR(100) NOT NULL,
    stat_value_text VARCHAR(100),
    stat_value_number DOUBLE PRECISION,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_fixture_team_stat
        UNIQUE (fixture_id, team_id, stat_name)
);

CREATE INDEX idx_fixture_team_stat_fixture ON fixture_team_stat(fixture_id);
CREATE INDEX idx_fixture_team_stat_team ON fixture_team_stat(team_id);
CREATE INDEX idx_fixture_team_stat_name ON fixture_team_stat(stat_name);